#!/bin/bash

server=./node_modules/.bin/webpack-dev-server

cp ./node_modules/pdfjs-dist/build/pdf.js ./examples/
cp ./node_modules/pdfjs-dist/build/pdf.worker.js ./examples/
cp ./node_modules/pdfjs-dist/web/pdf_viewer.js ./examples/
cp ./node_modules/pdfjs-dist/web/pdf_viewer.css ./examples/

$server --inline --config ./webpack.example.js --content-base examples/
